version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=apigateway,lambda,sqs,dynamodb,s3,events,kafka
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
