name: Deploy Gemini Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'Terraform_lambda_gemini/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform_lambda_gemini

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies into /python folder
        run: |
          mkdir -p python
          pip install -r requirements.txt -t python/

      - name: Zip /python folder for Lambda layer
        run: zip -r python.zip python/

      - name: Zip Lambda function code into main.zip
        run: zip main.zip main.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform_lambda_gemini/terraform
      - name: Check if IAM role is in state
        id: check_role
        continue-on-error: true
        run: terraform state show aws_iam_role.lambda_exec_role
        working-directory: Terraform_lambda_gemini/terraform

      - name: Import IAM role if not found in state
        if: steps.check_role.outcome == 'failure'
        run: terraform import aws_iam_role.lambda_exec_role lambda_exec_role
        working-directory: Terraform_lambda_gemini/terraform

      - name: Terraform Plan
        run: terraform plan -var="gemini_api_key=${{ secrets.GEMINI_API_KEY }}" -out=tfplan
        working-directory: Terraform_lambda_gemini/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: Terraform_lambda_gemini/terraform
