name: Deploy to AWS Lambda with Terraform

on:
  push:
    paths:
      - 'AWS_Examples/Terraform_lambda/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies into /python folder
        run: |
          mkdir -p python
          pip install -r requirements.txt -t python/

      - name: Zip /python folder for Lambda layer
        run: zip -r python.zip python/

      - name: Zip Lambda function code into main.zip
        run: zip main.zip main.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var="gemini_api_key=${{ secrets.GEMINI_API_KEY }}" -out=tfplan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform
